config/routes.rb
Rails.application.routes.draw do
 
	resources :forums do
	 resources :comments
end

    controller :sessions do
		get 'login'=> :new
		post 'login'=> :create
		get 'logout'=> :destroy
		delete 'logout'=> :destroy
	end
	
	resources :comments do
	put :upvote
	end
	
	

  get 'pages/home'

  get 'pages/about'
  
  get 'search', :to=> 'users#search'

  get 'upvote', :to=>'comments#upvote'
  
  resources :leaderboards
  resources :users
  resources :comments
  resources :forums

  root :to => 'pages#home'
  

end

app/models/forum.rb
class Forum < ActiveRecord::Base
	has_many:comments,  dependent: :destroy
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  before_action :set_forum, only: [:show, :edit, :update, :destroy]

  # GET /forums
  # GET /forums.json
  def index
    @forums = Forum.all
  end

  # GET /forums/1
  # GET /forums/1.json
  def show
  end

  # GET /forums/new
  def new
    @forum = Forum.new
  end

  # GET /forums/1/edit
  def edit
  end

  # POST /forums
  # POST /forums.json
  def create
    @forum = Forum.new(forum_params)

    respond_to do |format|
      if @forum.save
        format.html { redirect_to @forum, notice: 'Forum was successfully created.' }
        format.json { render :show, status: :created, location: @forum }
      else
        format.html { render :new }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forums/1
  # PATCH/PUT /forums/1.json
  def update
    respond_to do |format|
      if @forum.update(forum_params)
        format.html { redirect_to @forum, notice: 'Forum was successfully updated.' }
        format.json { render :show, status: :ok, location: @forum }
      else
        format.html { render :edit }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forums/1
  # DELETE /forums/1.json
  def destroy
    @forum.destroy
    respond_to do |format|
      format.html { redirect_to forums_url, notice: 'Forum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forum
      @forum = Forum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forum_params
      params.require(:forum).permit(:characterName, :characterPicture)
    end
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/_form.html.erb
<%if admin?%>

<%= form_for(@forum) do |f| %>
  <% if @forum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forum.errors.count, "error") %> prohibited this forum from being saved:</h2>

      <ul>
      <% @forum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :characterName %><br>
    <%= f.text_field :characterName %>
  </div>
  <div class="field">
    <%= f.label :characterPicture %><br>
    <%= f.text_field :characterPicture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<% else%>
<h1>You do not have access to this page</h1> 
<% end %>

app/views/forums/edit.html.erb
<h1>Editing Forum</h1>

<%= render 'form' %>

<%= link_to 'Show', @forum %> |
<%= link_to 'Back', forums_path %>

app/views/forums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Forums</h1>

<table class ="table">
	
  <tbody>
    <% @forums.each do |forum| %>
      <tr>
        <td><h3><%= forum.characterName %></h3></td>
        <td><%= image_tag(forum.characterPicture, :alt => "Could not find image", :size=>"300x150") %></td>
        <td><h3><%= link_to 'Enter Forum', forum %></h3></td>
		
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%if admin?%>
 <%= link_to 'New Forum', new_forum_path %>
<% end%>

app/views/forums/new.html.erb
<h1>New Forum</h1>

<%= render 'form' %>

<%= link_to 'Back', forums_path %>

app/views/forums/show.html.erb
<p id="notice"><%= notice %></p>
	<center>
<p>
  <h2><%= @forum.characterName %></h2>
</p>

<p>
	
  <%= image_tag(@forum.characterPicture, :alt => "Could not find image", :size=>"300x150") %>
  </br>
 </p>
 
	<%= form_for([@forum, Comment.new]) do|f| %>
	<%=f.text_area :content, :rows=>4, :cols=>40%>
		<div class = "actions">
			<%=f.submit "Post a Comment"%>
		</div>
	 <%end%>

	<%if@forum.comments.empty?%>
		<h3> You are the first to comment</h3>
	<%else%>
	
		<h2>All Comments</h2>
		<br>
		<%@forum.comments.reverse.each do |comment| %>
			<p>Posted by: <%= comment.user.username %>
			<br>
			--------------------------------
			<br>
			<strong>		<%=comment.content%> </strong>
			<br>
			--------------------------------
			<br>
			Posted: <%=time_ago_in_words(comment.created_at)%> - Up Votes: <%=comment.upVote%>
			<%if signed_in?%>
			<%= button_to 'Up Vote', comment_upvote_path(comment.id), method: :put %>
			<%end%>
			</p>
			<br>
		<%end%>
		
	<%end%>


<h4><%= link_to 'Back', forums_path %></h4>
	</center>