config/routes.rb
Rails.application.routes.draw do
 
	resources :forums do
	 resources :comments
end

    controller :sessions do
		get 'login'=> :new
		post 'login'=> :create
		get 'logout'=> :destroy
		delete 'logout'=> :destroy
	end
	
	resources :comments do
	put :upvote
	end
	
	

  get 'pages/home'

  get 'pages/about'
  
  get 'search', :to=> 'users#search'

  get 'upvote', :to=>'comments#upvote'
  
  resources :leaderboards
  resources :users
  resources :comments
  resources :forums

  root :to => 'pages#home'
  

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	belongs_to:leaderboard
	has_many:comments,  dependent: :destroy
	
	validates :email, uniqueness: true
	validates :email, presence: true
	validates :username, uniqueness: true
	validates :username, presence: true
	
	geocoded_by :address
	after_validation :geocode, :if => :address_changed?
	
	def self.search(query)
		where("username LIKE ?", "%#{query}%")
	end
	
	def age
		age = ((Time.now - created_at) /60 /60 /24).round
		return age
	end
	
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end
  
  def search
	@users = User.search params[:query]
	unless @users.empty?
		render'index'
	else
		flash[:notice] = 'No record matches that search'
		render 'index'
	end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
		Usermailer.welcome(@user).deliver
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation, :favouriteCharacter, :leaderboard_id, :email, :address, :latitude, :longitude)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :favourite_Character %><br>
    <%= f.text_field :favouriteCharacter %>
  </div>
  <div class="field">
    <%= f.label :leaderboard_id %><br>
	<%= f.collection_select:leaderboard_id, Leaderboard.all, :id, :rankDivision%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_search.html.erb

<%= form_tag(search_path, method: :get)do%>
	<%= text_field_tag(:query, params[:query])%>
	<%= submit_tag "Search"%>
<%end%>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table class ="table">
  <thead>
    <tr>
      <th>Username</th>
	  <th>Email</th>
	  <th>Address</th>
      <th>Favourite character</th>
      <th>Rank</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
		<td><%= user.email %></td>
		<td><%= user.address %></td>
        <td><%= user.favouriteCharacter %></td>
        <td><%= user.leaderboard.rankDivision %></td>
		<%if admin?%>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%if admin?%>
<%= link_to 'New User', new_user_path %>
<%end%>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>Favourite character:</strong>
  <%= @user.favouriteCharacter %>
</p>

<p>
  <strong>Rank:</strong>
   <%= @user.leaderboard.rankDivision%>
</p>

<p>
  <strong>Account Age:</strong>
    <%= @user.age%> Days
</p>
<p>
<strong>Your Address:</strong>
<%= image_tag"http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@user.latitude}%2C#{@user.longitude}" %>
</p>
<%= link_to 'Edit Account', edit_user_path(@user) %> |

<%if admin?%>
<%= link_to 'See all users', users_path %>
<%end%>