config/routes.rb
Rails.application.routes.draw do
 
	resources :forums do
	 resources :comments
end

    controller :sessions do
		get 'login'=> :new
		post 'login'=> :create
		get 'logout'=> :destroy
		delete 'logout'=> :destroy
	end
	
	resources :comments do
	put :upvote
	end
	
	

  get 'pages/home'

  get 'pages/about'
  
  get 'search', :to=> 'users#search'

  get 'upvote', :to=>'comments#upvote'
  
  resources :leaderboards
  resources :users
  resources :comments
  resources :forums

  root :to => 'pages#home'
  

end

app/views/layouts/_search.html.erb

<%= form_tag(search_path, method: :get)do%>
	<%= text_field_tag(:query, params[:query])%>
	<%= submit_tag "Search"%>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gameweb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<style>
body{
background-color:#C0C0C0	
}
h5
	{
	color:  #c0c0c0
	}
	
</style>


<div id = "banner">
	
	<%= "Level Up Forums" %>
</div>


<nav class="navbar navbar-inverse">
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%=link_to "Home", root_path%></li>
		<li><%=link_to "Forums", forums_path%></li>
		<li><%=link_to "Leaderboards", leaderboards_path%></li>
		
		<li><h5>Search for a Friend! Enter their username: </h5><%= render 'users/search' %>  </li>
		
		</ul>
        
     
      
      <ul class="nav navbar-nav navbar-right">
		<%if signed_in? %>
			<li><h5>Signed in as <%= @current_user.username%></h5></li>
		<%end%>
        <li class="Account">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
          <ul class="dropdown-menu">
		    <%if !signed_in? %>
				<li><%=link_to "Login", login_path%></li>
			<%else%>
				<li><%=link_to "Sign Out", logout_path%></li>
				<li><%=link_to "Manage Account", user_path(@current_user)%></li>
			<%end%>
            <li role="separator" class="divider"></li>
            <li><%=link_to "Create Account", new_user_path%></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<%= yield %>

</body>
</html>